### ISSUE TITLE
[Feature] Tooltips

### ISSUE THREAD

**Issue by davegomez** [davegomez/silky-charts#1]
Sometimes the simple data representation is not enough to give the reader an insightful idea of what the data is trying to represent. In these cases the tooltips are a great way to give more context in order to make the understanding process of the data simpler and faster.

I want to propose "three types" of tooltips for Silky Charts, each type will adapt to a different situation, type of data, and type of chart.

### Tooltip
The simplest form of the tooltip consisting of only one data element which display the data value and the reference to that value (string or date).

![image](https://user-images.githubusercontent.com/282903/53262785-8deaf480-36a5-11e9-8b3b-2dfd1d2d159f.png)

### Group Tooltip

Some charts offer the ability to compare different set of data over time like StackedArea or Line charts, in these cases a simple tooltip might not be enough to understand the dataset in an specific point represented in the chart. In these cases a tooltip showing a group of values with its corresponding reference might be more of value than a single one.

![image](https://user-images.githubusercontent.com/282903/53263503-93493e80-36a7-11e9-9b59-2ce4bf43a0fd.png)

### Static Tooltip

By default all the tooltip will be display during the onMouseEnter event and positioned on top of the mouse cursor but this could be distracting or undesirable in some cases that's why is important to have an static tooltip the developer can position anywhere in the chart and keeps steady until the onMouseEvent if triggered.

Also is important updating the content dynamically on mouse movement in charts like StackedArea where you can move the mouse over a whole area of data.

![image](https://user-images.githubusercontent.com/282903/53263629-fd61e380-36a7-11e9-8076-050c96a0d067.png)

## ToDo
- [x] Update current tooltip design [[card-17998312](https://github.com/davegomez/silky-charts/projects/1#card-17998312)]
- [x] Create group tooltip component which should display all datasets related with the specific position of the mouse relative to the main axis [[card-17998404](https://github.com/davegomez/silky-charts/projects/1#card-17998404)]
- [x] Build the `stacticTooltip` option adding access to this prop which will accepts the position of the tooltip as a value or defaults to `top-left` [[card-17998444](https://github.com/davegomez/silky-charts/projects/1#card-17998444)]. The available positions will be:
  * `top-left`: positions the tooltip at the top left corder of the chart
  * `top-right`: positions the tooltip at the top right corder of the chart 
  * `bottom-right`: positions the tooltip at the bottom right corder of the chart
  * `bottom-left`: positions the tooltip at the bottom left corder of the chart
  * `on-element`: positions the tooltip at the top of the data element (i.e. bar)
